{% set version = "0.10.1" %}

package:
  name: composeml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/composeml/composeml-{{ version }}.tar.gz
  sha256: d87fc181be72fadec16ea0e44ebd363b4e2e3620c87c8b2cae6e236fd00761d4

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - pandas >=1.3.0
    - tqdm >=4.32.0
    - matplotlib >=3.3.3
    - seaborn >=0.11.0

test:
  commands:
    - pip check
  imports:
    - composeml
  requires:
    - pip

about:
  doc_url: https://compose.alteryx.com/
  dev_url: https://github.com/alteryx/compose
  home: https://compose.alteryx.com/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An open source python library for automated prediction engineering.
  description: | 
    Compose is a machine learning tool for automated prediction engineering. It allows you to structure prediction problems
    and generate labels for supervised learning. An end user defines an outcome of interest by writing a labeling function, 
    then runs a search to automatically extract training examples from historical data. Its result is then provided to 
    Featuretools for automated feature engineering and subsequently to EvalML for automated machine learning


extra:
  recipe-maintainers:
    - jeff-hernandez
